CREATE TABLE `PRODUTO` (
  `ID_PRODUTO` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  `VALOR_UNITARIO` double NOT NULL,
  PRIMARY KEY (`ID_PRODUTO`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `CPF` varchar(11) NOT NULL,
  `TELEFONE` varchar(20) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

CREATE TABLE `PEDIDO` (
  `ID_PEDIDO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int(11) NOT NULL,
  `DATA_EMISSAO` date NOT NULL,
  `TOTAL` DECIMAL(13, 2) NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  KEY `ID_CLIENTE` (`ID_CLIENTE`),
  CONSTRAINT `PEDIDO_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID_CLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

CREATE TABLE `PEDIDO_ITEM` (
  `ID_PEDIDO_ITEM` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PEDIDO` int(11) NOT NULL,
  `ID_PRODUTO` int(11) NOT NULL,
  `VALOR_UNITARIO` DECIMAL(13, 2) NOT NULL,
  `QUANTIDADE` DECIMAL(13, 2) NOT NULL,
  `DESCONTO` DECIMAL(13, 2) NOT NULL,
  PRIMARY KEY (`ID_PEDIDO_ITEM`),
  KEY `ID_PEDIDO` (`ID_PEDIDO`),
  KEY `ID_PRODUTO` (`ID_PRODUTO`),
  CONSTRAINT `PEDIDO_ITEM_ibfk_1` FOREIGN KEY (`ID_PEDIDO`) REFERENCES `PEDIDO` (`ID_PEDIDO`),
  CONSTRAINT `PEDIDO_ITEM_ibfk_2` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID_PRODUTO`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;